export const ADD_DATA_DOCTOR_ONBOARD = "ADD_DATA_DOCTOR_ONBOARD";
export const EDIT_DOCTOR_DATA = "EDIT_DOCTOR_DATA";
export const DELETE_DOCTOR_DATA = "DELETE_DOCTOR_DATA";
export const GET_DOCTORS_DATA = "GET_DOCTORS_DATA";
